package org.tapestrycayenne.model.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.tapestrycayenne.model.Painting;

/**
 * Class _Bid was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Bid extends CayenneDataObject {

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String PAINTING_PROPERTY = "painting";

    public static final String BIDID_PK_COLUMN = "bidid";

    public void setAmount(BigDecimal amount) {
        writeProperty("amount", amount);
    }
    public BigDecimal getAmount() {
        return (BigDecimal)readProperty("amount");
    }

    public void setPainting(Painting painting) {
        setToOneTarget("painting", painting, true);
    }

    public Painting getPainting() {
        return (Painting)readProperty("painting");
    }


}
